-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 16:32:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tseedsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tseedsdb
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `tseedsdb` DEFAULT CHARACTER SET utf8 ;
-- USE `tseedsdb` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `iduser_norm` INT NOT NULL AUTO_INCREMENT,
  `iduser` BIGINT UNSIGNED NOT NULL,
  `screen_name` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NULL,
  `nro_tweets` INT NULL DEFAULT 0,
  `nro_retweets` INT NULL DEFAULT 0,
  `nro_mentions` INT NULL DEFAULT 0,
  `nro_replies` INT NULL DEFAULT 0,
  `nro_retweeted` INT NULL DEFAULT 0,
  `nro_mentioned` INT NULL DEFAULT 0,
  `nro_replied` INT NULL DEFAULT 0,
  `nro_seedset` INT NULL DEFAULT 0,
  `lang` VARCHAR(45) NULL,
  `location` VARCHAR(500) NULL,
  `intermediate` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_norm_UNIQUE` (`iduser_norm` ASC),
  UNIQUE INDEX `screen_name_UNIQUE` (`screen_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweet` (
  `idtweet` BIGINT UNSIGNED NOT NULL,
  `text` VARCHAR(500) NULL,
  `place` VARCHAR(500) NULL,
  `lang` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `millis` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtweet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actionlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actionlog` (
  `idlogentry` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `millis` BIGINT UNSIGNED NOT NULL,
  `type` ENUM('TWEET', 'RETWEET', 'REPLY') NOT NULL,
  `tweet_idtweet` BIGINT UNSIGNED NOT NULL,
  `user_iduser` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`tweet_idtweet`, `user_iduser`),
  INDEX `fk_actionlog_tweet1_idx` (`tweet_idtweet` ASC),
  INDEX `fk_actionlog_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_actionlog_tweet1`
    FOREIGN KEY (`tweet_idtweet`)
    REFERENCES `tweet` (`idtweet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actionlog_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seedset` (
  `idseedset` INT NOT NULL,
  `timeinit` TIMESTAMP NOT NULL,
  `millisinit` BIGINT UNSIGNED NOT NULL,
  `timeend` TIMESTAMP NOT NULL,
  `millisend` BIGINT UNSIGNED NOT NULL,
  `size` INT NOT NULL DEFAULT 0,
  `totalmarginf` DOUBLE NOT NULL DEFAULT 0,
  `totalusers` INT NOT NULL DEFAULT 0,
  `totalactions` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idseedset`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seed` (
  `seedset_idseedset` INT NOT NULL,
  `position` INT NOT NULL,
  `marginf` DOUBLE NOT NULL DEFAULT 0,
  `user_iduser` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`seedset_idseedset`, `user_iduser`),
  INDEX `fk_seed_seedset1_idx` (`seedset_idseedset` ASC),
  INDEX `fk_seed_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_seed_seedset1`
    FOREIGN KEY (`seedset_idseedset`)
    REFERENCES `seedset` (`idseedset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seed_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialgraph`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialgraph` (
  `user_follower` BIGINT UNSIGNED NOT NULL,
  `user_followed` BIGINT UNSIGNED NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `millis` BIGINT UNSIGNED NOT NULL,  
  PRIMARY KEY (`user_follower`, `user_followed`),
  INDEX `fk_socialgraph_user1_idx` (`user_follower` ASC),
  INDEX `fk_socialgraph_user2_idx` (`user_followed` ASC),
  CONSTRAINT `fk_socialgraph_user1`
    FOREIGN KEY (`user_follower`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socialgraph_user2`
    FOREIGN KEY (`user_followed`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
